// import './assets/main.css'

import { createApp } from 'vue'
import { createPinia } from 'pinia'
import Toast from "vue-toastification";

import 'bootstrap/dist/css/bootstrap.css' //引用bootstrap的样式
import 'bootstrap/dist/js/bootstrap.min.js' //引用bootstrap的js


import App from './App.vue'
import router from './router'

import axios from 'axios'
import VueAxios from 'vue-axios'

// import { TUIComponents, TUICore, genTestUserSig } from './TUIKit';
// import { TUICallKit } from '@tencentcloud/call-uikit-vue';

// // import { TUIComponents, TUICore, genTestUserSig } from './TUIKit';
// // // import TUICallKit
// // import { TUICallKit } from '@tencentcloud/call-uikit-vue';


// const SDKAppID = 1600008767; // Your SDKAppID
// const secretKey = '1006e9eba37917e3fc924ddabf9a0d2663200d620431d0a342e0d83c8199b98f'; //Your secretKey
// const userID = 'fatbear_user'; // User ID


// // init TUIKit
// const TUIKit = TUICore.init({
//   SDKAppID,
// });
// // TUIKit add TUIComponents
// TUIKit.use(TUIComponents);
// // TUIKit add TUICallKit
// TUIKit.use(TUICallKit);


// // login TUIKit
// TUIKit.login({
//   userID: userID,
//   userSig: genTestUserSig({
//     SDKAppID,
//     secretKey,
//     userID,
//   }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
// });


const app = createApp(App)

app.use(createPinia())
app.use(router)

app.use(VueAxios, axios)
app.provide('axios', app.config.globalProperties.axios)  // provide 'axios'

// const options: PluginOptions = {
//     // You can set your default options here
// };

app.use(Toast, {});
// app.use(TUIKit)

app.mount('#app')
